import type {
  FundComparisonRow,
  CompetitorComparisonRow,
  CompetitorSummary,
  CompetitorTimeSeries,
  CompetitiveFundsResponse,
  CompetitorComparisonResponse,
  CompetitiveNoteEntry,
} from '@/app/lib/types/competitive';

// ============================================================
// MOCK DATA — EQUITY COMPARISONS
// ============================================================

const mockEquityFunds: FundComparisonRow[] = [
  {
    id: 'VOO-vs-FMUS',
    rank: 1,
    category: 'US Equity',
    competitorTicker: 'VOO',
    competitorName: 'Vanguard S&P 500 ETF',
    competitorExpenseRatio: 0.03,
    competitorReturns: { oneYear: 26.4, threeYear: 10.1, fiveYear: 15.2, tenYear: 12.8 },
    competitorHoldings: 503,
    competitorPriceToBook: 4.5,
    competitorDividendYield: 1.32,
    firmTicker: 'FMUS',
    firmName: 'Firm US Core Equity Market ETF',
    firmExpenseRatio: 0.12,
    firmReturns: { oneYear: 27.1, threeYear: 10.8, fiveYear: 15.9, tenYear: 13.2 },
    firmHoldings: 3842,
    firmPriceToBook: 3.8,
    firmDividendYield: 1.45,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: true,
      priceToBook: false,
      dividendYield: true,
      total: 6,
      outOf: 8,
    },
    noteCount: 2,
  },
  {
    id: 'VTV-vs-FMLV',
    rank: 2,
    category: 'US Equity',
    competitorTicker: 'VTV',
    competitorName: 'Vanguard Value ETF',
    competitorExpenseRatio: 0.04,
    competitorReturns: { oneYear: 16.8, threeYear: 8.9, fiveYear: 10.1, tenYear: 9.4 },
    competitorHoldings: 342,
    competitorPriceToBook: 2.6,
    competitorDividendYield: 2.41,
    firmTicker: 'FMLV',
    firmName: 'Firm US Large Cap Value ETF',
    firmExpenseRatio: 0.24,
    firmReturns: { oneYear: 18.2, threeYear: 10.4, fiveYear: 11.3, tenYear: 10.1 },
    firmHoldings: 1247,
    firmPriceToBook: 1.9,
    firmDividendYield: 2.68,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: true,
      priceToBook: true,
      dividendYield: true,
      total: 7,
      outOf: 8,
    },
    noteCount: 3,
  },
  {
    id: 'IJR-vs-FMAS',
    rank: 3,
    category: 'US Equity',
    competitorTicker: 'IJR',
    competitorName: 'iShares Core S&P Small-Cap ETF',
    competitorExpenseRatio: 0.06,
    competitorReturns: { oneYear: 12.4, threeYear: 5.2, fiveYear: 9.8, tenYear: 8.9 },
    competitorHoldings: 602,
    competitorPriceToBook: 2.1,
    competitorDividendYield: 1.38,
    firmTicker: 'FMAS',
    firmName: 'Firm US Small Cap ETF',
    firmExpenseRatio: 0.27,
    firmReturns: { oneYear: 13.8, threeYear: 6.9, fiveYear: 10.6, tenYear: 9.5 },
    firmHoldings: 2156,
    firmPriceToBook: 1.8,
    firmDividendYield: 1.52,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: true,
      priceToBook: true,
      dividendYield: true,
      total: 7,
      outOf: 8,
    },
    noteCount: 1,
  },
  {
    id: 'IJS-vs-FMSV',
    rank: 4,
    category: 'US Equity',
    competitorTicker: 'IJS',
    competitorName: 'iShares S&P Small-Cap 600 Value ETF',
    competitorExpenseRatio: 0.18,
    competitorReturns: { oneYear: 10.2, threeYear: 6.1, fiveYear: 9.4, tenYear: 8.2 },
    competitorHoldings: 456,
    competitorPriceToBook: 1.5,
    competitorDividendYield: 1.74,
    firmTicker: 'FMSV',
    firmName: 'Firm US Small Cap Value ETF',
    firmExpenseRatio: 0.31,
    firmReturns: { oneYear: 12.6, threeYear: 8.7, fiveYear: 11.2, tenYear: 9.8 },
    firmHoldings: 1389,
    firmPriceToBook: 1.1,
    firmDividendYield: 2.01,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: true,
      priceToBook: true,
      dividendYield: true,
      total: 7,
      outOf: 8,
    },
    noteCount: 0,
  },
  {
    id: 'VXUS-vs-FMAI',
    rank: 5,
    category: 'Dev Ex US Equity',
    competitorTicker: 'VXUS',
    competitorName: 'Vanguard Total International Stock ETF',
    competitorExpenseRatio: 0.07,
    competitorReturns: { oneYear: 9.6, threeYear: 3.4, fiveYear: 6.8, tenYear: 5.2 },
    competitorHoldings: 8524,
    competitorPriceToBook: 1.9,
    competitorDividendYield: 3.12,
    firmTicker: 'FMAI',
    firmName: 'Firm International Core Equity Market ETF',
    firmExpenseRatio: 0.18,
    firmReturns: { oneYear: 10.4, threeYear: 4.6, fiveYear: 7.5, tenYear: 5.9 },
    firmHoldings: 7891,
    firmPriceToBook: 1.7,
    firmDividendYield: 3.28,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: false,
      priceToBook: false,
      dividendYield: true,
      total: 5,
      outOf: 8,
    },
    noteCount: 1,
  },
  {
    id: 'EFV-vs-FMIV',
    rank: 6,
    category: 'Dev Ex US Equity',
    competitorTicker: 'EFV',
    competitorName: 'iShares MSCI EAFE Value ETF',
    competitorExpenseRatio: 0.34,
    competitorReturns: { oneYear: 11.2, threeYear: 7.1, fiveYear: 6.9, tenYear: 4.8 },
    competitorHoldings: 478,
    competitorPriceToBook: 1.3,
    competitorDividendYield: 4.18,
    firmTicker: 'FMIV',
    firmName: 'Firm International Value ETF',
    firmExpenseRatio: 0.28,
    firmReturns: { oneYear: 13.1, threeYear: 8.9, fiveYear: 8.4, tenYear: 6.1 },
    firmHoldings: 1856,
    firmPriceToBook: 1.0,
    firmDividendYield: 4.42,
    firmWins: {
      expenseRatio: true,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: true,
      priceToBook: true,
      dividendYield: true,
      total: 8,
      outOf: 8,
    },
    noteCount: 2,
  },
  {
    id: 'VSS-vs-FISV',
    rank: 7,
    category: 'Dev Ex US Equity',
    competitorTicker: 'VSS',
    competitorName: 'Vanguard FTSE All-World ex-US Small-Cap ETF',
    competitorExpenseRatio: 0.07,
    competitorReturns: { oneYear: 8.1, threeYear: 1.9, fiveYear: 6.2, tenYear: 5.4 },
    competitorHoldings: 4672,
    competitorPriceToBook: 1.4,
    competitorDividendYield: 2.89,
    firmTicker: 'FISV',
    firmName: 'Firm International Small Cap Value ETF',
    firmExpenseRatio: 0.42,
    firmReturns: { oneYear: 9.7, threeYear: 4.2, fiveYear: 7.8, tenYear: 6.3 },
    firmHoldings: 3214,
    firmPriceToBook: 1.0,
    firmDividendYield: 3.14,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: false,
      priceToBook: true,
      dividendYield: true,
      total: 6,
      outOf: 8,
    },
    noteCount: 0,
  },
  {
    id: 'VWO-vs-FMAE',
    rank: 8,
    category: 'Emerging Markets Equity',
    competitorTicker: 'VWO',
    competitorName: 'Vanguard FTSE Emerging Markets ETF',
    competitorExpenseRatio: 0.08,
    competitorReturns: { oneYear: 11.8, threeYear: 1.2, fiveYear: 4.6, tenYear: 3.9 },
    competitorHoldings: 5847,
    competitorPriceToBook: 1.8,
    competitorDividendYield: 3.24,
    firmTicker: 'FMAE',
    firmName: 'Firm Emerging Markets Core Equity ETF',
    firmExpenseRatio: 0.36,
    firmReturns: { oneYear: 12.4, threeYear: 2.8, fiveYear: 5.9, tenYear: 4.6 },
    firmHoldings: 6128,
    firmPriceToBook: 1.5,
    firmDividendYield: 3.51,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: true,
      priceToBook: true,
      dividendYield: true,
      total: 7,
      outOf: 8,
    },
    noteCount: 0,
  },
  {
    id: 'SCHD-vs-FMAC',
    rank: 9,
    category: 'US Equity',
    competitorTicker: 'SCHD',
    competitorName: 'Schwab US Dividend Equity ETF',
    competitorExpenseRatio: 0.06,
    competitorReturns: { oneYear: 12.9, threeYear: 7.8, fiveYear: 12.4, tenYear: 11.6 },
    competitorHoldings: 104,
    competitorPriceToBook: 3.4,
    competitorDividendYield: 3.52,
    firmTicker: 'FMAC',
    firmName: 'Firm US Core Equity 2 ETF',
    firmExpenseRatio: 0.17,
    firmReturns: { oneYear: 24.8, threeYear: 9.6, fiveYear: 14.8, tenYear: 12.4 },
    firmHoldings: 2891,
    firmPriceToBook: 3.2,
    firmDividendYield: 1.38,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: true,
      priceToBook: false,
      dividendYield: false,
      total: 5,
      outOf: 8,
    },
    noteCount: 1,
  },
];

// ============================================================
// MOCK DATA — FIXED INCOME COMPARISONS
// ============================================================

const mockFixedIncomeFunds: FundComparisonRow[] = [
  {
    id: 'BND-vs-FMCF',
    rank: 1,
    category: 'Fixed Income',
    competitorTicker: 'BND',
    competitorName: 'Vanguard Total Bond Market ETF',
    competitorExpenseRatio: 0.03,
    competitorReturns: { oneYear: 2.1, threeYear: -1.8, fiveYear: 0.4, tenYear: 1.6 },
    competitorHoldings: 10742,
    competitorPriceToBook: null,
    competitorDividendYield: 3.42,
    firmTicker: 'FMCF',
    firmName: 'Firm California Municipal Bond ETF',
    firmExpenseRatio: 0.19,
    firmReturns: { oneYear: 3.2, threeYear: -0.6, fiveYear: 1.2, tenYear: 2.1 },
    firmHoldings: 1247,
    firmPriceToBook: null,
    firmDividendYield: 3.68,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: false,
      priceToBook: false,
      dividendYield: true,
      total: 5,
      outOf: 6,
    },
    noteCount: 1,
  },
  {
    id: 'BSV-vs-FMSD',
    rank: 2,
    category: 'Fixed Income',
    competitorTicker: 'BSV',
    competitorName: 'Vanguard Short-Term Bond ETF',
    competitorExpenseRatio: 0.04,
    competitorReturns: { oneYear: 4.2, threeYear: 1.1, fiveYear: 1.6, tenYear: 1.8 },
    competitorHoldings: 2872,
    competitorPriceToBook: null,
    competitorDividendYield: 3.18,
    firmTicker: 'FMSD',
    firmName: 'Firm Short-Duration Fixed Income ETF',
    firmExpenseRatio: 0.17,
    firmReturns: { oneYear: 4.8, threeYear: 1.9, fiveYear: 2.1, tenYear: 2.2 },
    firmHoldings: 864,
    firmPriceToBook: null,
    firmDividendYield: 3.45,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: false,
      priceToBook: false,
      dividendYield: true,
      total: 5,
      outOf: 6,
    },
    noteCount: 0,
  },
  {
    id: 'AGG-vs-FMCF2',
    rank: 3,
    category: 'Fixed Income',
    competitorTicker: 'AGG',
    competitorName: 'iShares Core U.S. Aggregate Bond ETF',
    competitorExpenseRatio: 0.03,
    competitorReturns: { oneYear: 2.0, threeYear: -1.9, fiveYear: 0.3, tenYear: 1.5 },
    competitorHoldings: 12145,
    competitorPriceToBook: null,
    competitorDividendYield: 3.38,
    firmTicker: 'FMCF',
    firmName: 'Firm California Municipal Bond ETF',
    firmExpenseRatio: 0.19,
    firmReturns: { oneYear: 3.2, threeYear: -0.6, fiveYear: 1.2, tenYear: 2.1 },
    firmHoldings: 1247,
    firmPriceToBook: null,
    firmDividendYield: 3.68,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: false,
      priceToBook: false,
      dividendYield: true,
      total: 5,
      outOf: 6,
    },
    noteCount: 0,
  },
  {
    id: 'VTIP-vs-FMIP',
    rank: 4,
    category: 'Fixed Income',
    competitorTicker: 'VTIP',
    competitorName: 'Vanguard Short-Term Inflation-Protected Securities ETF',
    competitorExpenseRatio: 0.04,
    competitorReturns: { oneYear: 3.6, threeYear: 2.1, fiveYear: 3.2, tenYear: 2.4 },
    competitorHoldings: 32,
    competitorPriceToBook: null,
    competitorDividendYield: 5.21,
    firmTicker: 'FMIP',
    firmName: 'Firm Inflation-Protected Securities ETF',
    firmExpenseRatio: 0.11,
    firmReturns: { oneYear: 3.9, threeYear: 2.4, fiveYear: 3.5, tenYear: 2.7 },
    firmHoldings: 48,
    firmPriceToBook: null,
    firmDividendYield: 5.48,
    firmWins: {
      expenseRatio: false,
      oneYear: true,
      threeYear: true,
      fiveYear: true,
      tenYear: true,
      holdings: true,
      priceToBook: false,
      dividendYield: true,
      total: 6,
      outOf: 6,
    },
    noteCount: 2,
  },
];

// ============================================================
// MOCK DATA — COMPETITOR COMPARISONS
// ============================================================

const mockCompetitorFunds: CompetitorComparisonRow[] = [
  {
    id: 'CPLV-vs-FMLV',
    category: 'US Equity',
    competitorTicker: 'CPLV',
    competitorName: 'Competitor U.S. Large Cap Value ETF',
    competitorExpenseRatio: 0.15,
    competitorReturns: { oneYear: 17.4, threeYear: 9.8, fiveYear: 10.6, tenYear: null, sinceCommonInception: 12.1 },
    competitorCharacteristics: { holdings: 482, marketCap: '$148.2B', priceToBook: 2.4, profitability: 2.81, valueAllocation: 68, growthAllocation: 8 },
    firmTicker: 'FMLV',
    firmName: 'Firm US Large Cap Value ETF',
    firmExpenseRatio: 0.24,
    firmReturns: { oneYear: 18.2, threeYear: 10.4, fiveYear: 11.3, tenYear: null, sinceCommonInception: 12.8 },
    firmCharacteristics: { holdings: 1247, marketCap: '$126.8B', priceToBook: 1.9, profitability: 3.24, valueAllocation: 78, growthAllocation: 3 },
    commonInceptionDate: 'Sep 2021',
    firmWinsOneYear: true,
    firmWinsThreeYear: true,
    firmWinsFiveYear: true,
    firmWinsTenYear: null,
    firmWinsSinceInception: true,
    firmWinsExpenseRatio: false,
    noteCount: 2,
  },
  {
    id: 'CPUV-vs-FMSV',
    category: 'US Equity',
    competitorTicker: 'CPUV',
    competitorName: 'Competitor U.S. Small Cap Value ETF',
    competitorExpenseRatio: 0.25,
    competitorReturns: { oneYear: 13.8, threeYear: 9.2, fiveYear: 12.4, tenYear: null, sinceCommonInception: 14.6 },
    competitorCharacteristics: { holdings: 734, marketCap: '$4.1B', priceToBook: 1.3, profitability: 2.46, valueAllocation: 82, growthAllocation: 2 },
    firmTicker: 'FMSV',
    firmName: 'Firm US Small Cap Value ETF',
    firmExpenseRatio: 0.31,
    firmReturns: { oneYear: 12.6, threeYear: 8.7, fiveYear: 11.2, tenYear: null, sinceCommonInception: 13.9 },
    firmCharacteristics: { holdings: 1389, marketCap: '$3.2B', priceToBook: 1.1, profitability: 2.68, valueAllocation: 88, growthAllocation: 1 },
    commonInceptionDate: 'Sep 2019',
    firmWinsOneYear: false,
    firmWinsThreeYear: false,
    firmWinsFiveYear: false,
    firmWinsTenYear: null,
    firmWinsSinceInception: false,
    firmWinsExpenseRatio: false,
    noteCount: 3,
  },
  {
    id: 'CPDV-vs-FMIV',
    category: 'Dev Ex US Equity',
    competitorTicker: 'CPDV',
    competitorName: 'Competitor International Small Cap Value ETF',
    competitorExpenseRatio: 0.36,
    competitorReturns: { oneYear: 12.1, threeYear: 7.4, fiveYear: 7.8, tenYear: null, sinceCommonInception: 9.2 },
    competitorCharacteristics: { holdings: 1342, marketCap: '$28.4B', priceToBook: 1.1, profitability: 2.23, valueAllocation: 74, growthAllocation: 5 },
    firmTicker: 'FMIV',
    firmName: 'Firm International Value ETF',
    firmExpenseRatio: 0.28,
    firmReturns: { oneYear: 13.1, threeYear: 8.9, fiveYear: 8.4, tenYear: null, sinceCommonInception: 9.8 },
    firmCharacteristics: { holdings: 1856, marketCap: '$24.1B', priceToBook: 1.0, profitability: 2.51, valueAllocation: 81, growthAllocation: 2 },
    commonInceptionDate: 'Sep 2019',
    firmWinsOneYear: true,
    firmWinsThreeYear: true,
    firmWinsFiveYear: true,
    firmWinsTenYear: null,
    firmWinsSinceInception: true,
    firmWinsExpenseRatio: true,
    noteCount: 1,
  },
  {
    id: 'CPES-vs-FMAE',
    category: 'Emerging Markets Equity',
    competitorTicker: 'CPES',
    competitorName: 'Competitor Emerging Markets Equity ETF',
    competitorExpenseRatio: 0.33,
    competitorReturns: { oneYear: 11.9, threeYear: 2.4, fiveYear: 5.2, tenYear: null, sinceCommonInception: 6.8 },
    competitorCharacteristics: { holdings: 3847, marketCap: '$18.6B', priceToBook: 1.6, profitability: 1.98, valueAllocation: 52, growthAllocation: 14 },
    firmTicker: 'FMAE',
    firmName: 'Firm Emerging Markets Core Equity ETF',
    firmExpenseRatio: 0.36,
    firmReturns: { oneYear: 12.4, threeYear: 2.8, fiveYear: 5.9, tenYear: null, sinceCommonInception: 7.1 },
    firmCharacteristics: { holdings: 6128, marketCap: '$15.2B', priceToBook: 1.5, profitability: 2.14, valueAllocation: 56, growthAllocation: 11 },
    commonInceptionDate: 'Nov 2020',
    firmWinsOneYear: true,
    firmWinsThreeYear: true,
    firmWinsFiveYear: true,
    firmWinsTenYear: null,
    firmWinsSinceInception: true,
    firmWinsExpenseRatio: false,
    noteCount: 0,
  },
  {
    id: 'CPUS-vs-FMAC',
    category: 'US Equity',
    competitorTicker: 'CPUS',
    competitorName: 'Competitor U.S. Equity ETF',
    competitorExpenseRatio: 0.15,
    competitorReturns: { oneYear: 25.6, threeYear: 10.2, fiveYear: 15.1, tenYear: null, sinceCommonInception: 14.2 },
    competitorCharacteristics: { holdings: 2156, marketCap: '$215.4B', priceToBook: 3.6, profitability: 3.02, valueAllocation: 32, growthAllocation: 28 },
    firmTicker: 'FMAC',
    firmName: 'Firm US Core Equity 2 ETF',
    firmExpenseRatio: 0.17,
    firmReturns: { oneYear: 24.8, threeYear: 9.6, fiveYear: 14.8, tenYear: null, sinceCommonInception: 13.8 },
    firmCharacteristics: { holdings: 2891, marketCap: '$198.6B', priceToBook: 3.2, profitability: 3.18, valueAllocation: 36, growthAllocation: 24 },
    commonInceptionDate: 'Sep 2019',
    firmWinsOneYear: false,
    firmWinsThreeYear: false,
    firmWinsFiveYear: false,
    firmWinsTenYear: null,
    firmWinsSinceInception: false,
    firmWinsExpenseRatio: false,
    noteCount: 1,
  },
  {
    id: 'CPIG-vs-FMCF',
    category: 'Core',
    competitorTicker: 'CPIG',
    competitorName: 'Competitor Core Fixed Income ETF',
    competitorExpenseRatio: 0.15,
    competitorReturns: { qtd: 1.1, ytd: 1.1, oneYear: 2.8, threeYear: -0.9, fiveYear: 0.8, tenYear: null, sinceCommonInception: 1.4 },
    competitorCharacteristics: { holdings: null, marketCap: null, priceToBook: null, profitability: null, valueAllocation: null, growthAllocation: null, duration: 6.1, secYield: 4.52 },
    firmTicker: 'FMCF',
    firmName: 'Firm California Municipal Bond ETF',
    firmExpenseRatio: 0.19,
    firmReturns: { qtd: 1.4, ytd: 1.4, oneYear: 3.2, threeYear: -0.6, fiveYear: 1.2, tenYear: null, sinceCommonInception: 1.8 },
    firmCharacteristics: { holdings: null, marketCap: null, priceToBook: null, profitability: null, valueAllocation: null, growthAllocation: null, duration: 5.8, secYield: 3.21 },
    commonInceptionDate: 'Jun 2020',
    firmWinsOneYear: true,
    firmWinsThreeYear: true,
    firmWinsFiveYear: true,
    firmWinsTenYear: null,
    firmWinsSinceInception: true,
    firmWinsExpenseRatio: false,
    noteCount: 0,
  },
  {
    id: 'CPSF-vs-FMSD',
    category: 'Short-Term',
    competitorTicker: 'CPSF',
    competitorName: 'Competitor Short-Term Fixed Income ETF',
    competitorExpenseRatio: 0.15,
    competitorReturns: { qtd: 1.3, ytd: 1.3, oneYear: 4.5, threeYear: 1.6, fiveYear: 1.9, tenYear: null, sinceCommonInception: 2.0 },
    competitorCharacteristics: { holdings: null, marketCap: null, priceToBook: null, profitability: null, valueAllocation: null, growthAllocation: null, duration: 2.0, secYield: 4.78 },
    firmTicker: 'FMSD',
    firmName: 'Firm Short-Duration Fixed Income ETF',
    firmExpenseRatio: 0.17,
    firmReturns: { qtd: 1.5, ytd: 1.5, oneYear: 4.8, threeYear: 1.9, fiveYear: 2.1, tenYear: null, sinceCommonInception: 2.3 },
    firmCharacteristics: { holdings: null, marketCap: null, priceToBook: null, profitability: null, valueAllocation: null, growthAllocation: null, duration: 1.9, secYield: 4.61 },
    commonInceptionDate: 'Nov 2020',
    firmWinsOneYear: true,
    firmWinsThreeYear: true,
    firmWinsFiveYear: true,
    firmWinsTenYear: null,
    firmWinsSinceInception: true,
    firmWinsExpenseRatio: false,
    noteCount: 0,
  },
];

const mockCompetitorSummary: CompetitorSummary = {
  totalComparisons: 7,
  firmWinning: 3,
  competitorWinning: 2,
  tied: 1,
};

const mockCompetitorTimeSeries: CompetitorTimeSeries[] = [
  { date: 'Jan 2024', firmWins: 3, competitorWins: 2, delta: 1 },
  { date: 'Feb 2024', firmWins: 3, competitorWins: 2, delta: 1 },
  { date: 'Mar 2024', firmWins: 4, competitorWins: 2, delta: 2 },
  { date: 'Apr 2024', firmWins: 4, competitorWins: 2, delta: 2 },
  { date: 'May 2024', firmWins: 3, competitorWins: 3, delta: 0 },
  { date: 'Jun 2024', firmWins: 3, competitorWins: 3, delta: 0 },
  { date: 'Jul 2024', firmWins: 4, competitorWins: 2, delta: 2 },
  { date: 'Aug 2024', firmWins: 4, competitorWins: 2, delta: 2 },
  { date: 'Sep 2024', firmWins: 3, competitorWins: 2, delta: 1 },
  { date: 'Oct 2024', firmWins: 3, competitorWins: 3, delta: 0 },
  { date: 'Nov 2024', firmWins: 4, competitorWins: 2, delta: 2 },
  { date: 'Dec 2024', firmWins: 4, competitorWins: 1, delta: 3 },
  { date: 'Jan 2025', firmWins: 3, competitorWins: 2, delta: 1 },
  { date: 'Feb 2025', firmWins: 3, competitorWins: 2, delta: 1 },
  { date: 'Mar 2025', firmWins: 3, competitorWins: 2, delta: 1 },
];

// ============================================================
// MOCK NOTES DATA
// ============================================================

let mockNotes: CompetitiveNoteEntry[] = [
  { id: 1, fundId: 'VOO-vs-FMUS', noteText: 'VOO is the #1 held ETF in client models. Biggest AUM gap but the firm outperforms on returns. Strong story for tilted exposure.', authorName: 'Eli F.', authorId: 'user-1', createdAt: '2025-03-15T14:30:00Z' },
  { id: 2, fundId: 'VOO-vs-FMUS', noteText: 'Sales team should emphasize the 3,800+ holdings advantage for diversification pitch.', authorName: 'Sarah K.', authorId: 'user-2', createdAt: '2025-03-18T09:15:00Z' },
  { id: 3, fundId: 'VTV-vs-FMLV', noteText: 'The firm wins 7/8 metrics here. This is our strongest value story. The deeper value tilt (P/B 1.9 vs 2.6) is the key differentiator.', authorName: 'Eli F.', authorId: 'user-1', createdAt: '2025-03-10T11:00:00Z' },
  { id: 4, fundId: 'VTV-vs-FMLV', noteText: 'Confirmed with product team — FMLV captures more of the value premium than VTV due to profitability screens.', authorName: 'Mike R.', authorId: 'user-3', createdAt: '2025-03-12T16:45:00Z' },
  { id: 5, fundId: 'VTV-vs-FMLV', noteText: 'Adding this to the Q2 campaign target list. Broker-Dealer team has seen high interest in value rotation.', authorName: 'Sarah K.', authorId: 'user-2', createdAt: '2025-03-20T10:30:00Z' },
  { id: 6, fundId: 'IJR-vs-FMAS', noteText: 'IJR uses S&P 600 which has profitability screens. Worth noting this is not a pure index comparison.', authorName: 'Mike R.', authorId: 'user-3', createdAt: '2025-02-28T14:00:00Z' },
  { id: 7, fundId: 'VXUS-vs-FMAI', noteText: 'International space is where expense ratio gap is smallest. Focus pitch on returns and deeper value/small exposure.', authorName: 'Eli F.', authorId: 'user-1', createdAt: '2025-03-05T09:00:00Z' },
  { id: 8, fundId: 'EFV-vs-FMIV', noteText: 'Perfect score — the firm wins all 8 metrics including expense ratio. Use this as the showcase comparison.', authorName: 'Eli F.', authorId: 'user-1', createdAt: '2025-03-08T13:20:00Z' },
  { id: 9, fundId: 'EFV-vs-FMIV', noteText: 'IAG team confirmed multiple RFPs where intl value has come up. Prioritize for advisor outreach.', authorName: 'Sarah K.', authorId: 'user-2', createdAt: '2025-03-22T11:15:00Z' },
  { id: 10, fundId: 'SCHD-vs-FMAC', noteText: 'SCHD is popular for dividend focus. Different approach than FMAC — be careful positioning as direct replacement.', authorName: 'Mike R.', authorId: 'user-3', createdAt: '2025-03-01T10:00:00Z' },
  { id: 11, fundId: 'BND-vs-FMCF', noteText: 'Fixed income comparisons are tricky due to different benchmark approaches. The firm focuses on credit quality.', authorName: 'Eli F.', authorId: 'user-1', createdAt: '2025-03-14T15:00:00Z' },
  { id: 12, fundId: 'VTIP-vs-FMIP', noteText: 'With inflation concerns rising, this comparison is getting more traction. Both solid options but the firm edges on returns.', authorName: 'Sarah K.', authorId: 'user-2', createdAt: '2025-03-19T08:45:00Z' },
  { id: 13, fundId: 'VTIP-vs-FMIP', noteText: 'FMIP has broader TIPS exposure across maturities which may help in various rate environments.', authorName: 'Mike R.', authorId: 'user-3', createdAt: '2025-03-21T14:30:00Z' },
  { id: 14, fundId: 'CPLV-vs-FMLV', noteText: 'This is our closest competitor in the value space. FMLV still outperforms on deeper value tilt.', authorName: 'Eli F.', authorId: 'user-1', createdAt: '2025-03-11T10:30:00Z' },
  { id: 15, fundId: 'CPLV-vs-FMLV', noteText: 'Key talking point: FMLV has been around longer with a more established track record.', authorName: 'Sarah K.', authorId: 'user-2', createdAt: '2025-03-16T09:00:00Z' },
  { id: 16, fundId: 'CPUV-vs-FMSV', noteText: 'This is where the competitor genuinely outperforms. CPUV has better returns across all periods. Acknowledge and redirect to other strengths.', authorName: 'Eli F.', authorId: 'user-1', createdAt: '2025-03-07T11:00:00Z' },
  { id: 17, fundId: 'CPUV-vs-FMSV', noteText: 'Product team aware of the gap. New factor tilts being evaluated for FMSV enhancement.', authorName: 'Mike R.', authorId: 'user-3', createdAt: '2025-03-13T16:00:00Z' },
  { id: 18, fundId: 'CPUV-vs-FMSV', noteText: 'When advisors bring up CPUV, pivot to the broader firm ecosystem advantage and model-level benefits.', authorName: 'Sarah K.', authorId: 'user-2', createdAt: '2025-03-25T10:15:00Z' },
  { id: 19, fundId: 'CPDV-vs-FMIV', noteText: 'The firm wins across the board here including on fees. Strong comparison to lead with.', authorName: 'Eli F.', authorId: 'user-1', createdAt: '2025-03-09T14:45:00Z' },
  { id: 20, fundId: 'CPUS-vs-FMAC', noteText: 'Competitor edges the firm on US core — small margin but consistent. Not a priority campaign target.', authorName: 'Mike R.', authorId: 'user-3', createdAt: '2025-03-17T13:00:00Z' },
];

let nextNoteId = 21;

// ============================================================
// SIMULATED DELAY
// ============================================================

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

// ============================================================
// API FUNCTIONS
// ============================================================

export async function getEquityComparisons(): Promise<CompetitiveFundsResponse> {
  await delay(400);
  return {
    funds: [...mockEquityFunds].sort((a, b) => {
      const scoreDiff = (b.firmWins.total / b.firmWins.outOf) - (a.firmWins.total / a.firmWins.outOf);
      if (scoreDiff !== 0) return scoreDiff;
      return a.competitorTicker.localeCompare(b.competitorTicker);
    }).map((f, i) => ({ ...f, rank: i + 1 })),
    total: mockEquityFunds.length,
    asOfDate: 'Mar 31, 2025',
  };
}

export async function getFixedIncomeComparisons(): Promise<CompetitiveFundsResponse> {
  await delay(400);
  return {
    funds: [...mockFixedIncomeFunds].sort((a, b) => {
      const scoreDiff = (b.firmWins.total / b.firmWins.outOf) - (a.firmWins.total / a.firmWins.outOf);
      if (scoreDiff !== 0) return scoreDiff;
      return a.competitorTicker.localeCompare(b.competitorTicker);
    }).map((f, i) => ({ ...f, rank: i + 1 })),
    total: mockFixedIncomeFunds.length,
    asOfDate: 'Mar 31, 2025',
  };
}

export async function getCompetitorComparisons(): Promise<CompetitorComparisonResponse> {
  await delay(400);
  return {
    funds: mockCompetitorFunds,
    summary: mockCompetitorSummary,
    timeSeries: mockCompetitorTimeSeries,
    asOfDate: 'Mar 31, 2025',
  };
}

// ============================================================
// NOTES API FUNCTIONS
// ============================================================

export async function getCompetitiveFundNotes(fundId: string): Promise<CompetitiveNoteEntry[]> {
  await delay(200);
  return mockNotes.filter(n => n.fundId === fundId).sort((a, b) =>
    new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
  );
}

export async function addCompetitiveFundNote(fundId: string, noteText: string): Promise<CompetitiveNoteEntry> {
  await delay(200);
  const entry: CompetitiveNoteEntry = {
    id: nextNoteId++,
    fundId,
    noteText,
    authorName: 'Eli F.',
    authorId: 'user-1',
    createdAt: new Date().toISOString(),
  };
  mockNotes.push(entry);
  return entry;
}

export async function updateCompetitiveFundNote(
  fundId: string,
  noteId: number,
  noteText: string
): Promise<CompetitiveNoteEntry> {
  await delay(200);
  const idx = mockNotes.findIndex(n => n.id === noteId && n.fundId === fundId);
  if (idx === -1) throw new Error('Note not found');
  mockNotes[idx] = { ...mockNotes[idx], noteText };
  return mockNotes[idx];
}

export async function deleteCompetitiveFundNote(fundId: string, noteId: number): Promise<void> {
  await delay(200);
  mockNotes = mockNotes.filter(n => !(n.id === noteId && n.fundId === fundId));
}
